# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bill Charlaftis
title: DevOps Engineer, System's Architect and Team leader
email: charlaftisb@gmail.com
website: https://charlaftisbill.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  CharlaftisBill
linkedin_username: bill-charlaftis

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Bill and I'm a DevOps Engineer and System's Architect. I've plenty of experience on various DevOps tools and methodologies, as well as to (micro)sevices designee practices.

  I am most skilled in: <b>Docker</b> and <b>Ansible</b>

content:
  - title: Professional Experience
    layout: text
    content: | # this will include new lines to allow paragraphs
      - <b>Team leading</b> duties,
      - Experienced <b>microservices</b> architect,
      - <b>Debian based Linux</b> user since 2013 and <b>administrator</b> since 2016,
      - Hands on experience with <b>system automation friendly</b> scripting languages such as <b>Bash, Python3, Node.js (Typescript)</b>,
      - Daily user of <b>Ansible</b> provision tool to setup On-Premise servers,
      - Solid understanding of <b>DevOps</b> main principles (Plan, Build, Test, Package, Deploy, Configure, Monitor) ,
      - Deep knowledge of <b>Docker</b> containerization technology,
      - Maintainer of 8 <b>Docker Swarm</b> clusters of 3 <b>managers</b> and 2 <b>workers</b> each running on <b>DigitalOcean and On-Premise</b>,
      - In depth understanding of <b>Network protocols</b> such as SSH, TCP/UDP, HTTP(S), FTP(s), NFS, DHCP and many more,
      - Experienced in configuring web servers/load balancers/reverse proxies such as <b>Nginx</b> and <b>Apache</b>,
      - Strong understanding of <b>CI/CD</b> pipelines,
      - Familiar with <b>.Net Core</b> as I have worked as C# backend developer for about 1 year. 

  - title: Homelab Experience
    layout: text
    content: | # this will include new lines to allow paragraphs
      I have built a small cluster of Barebone PCs and Raspberry Pis at home. I use this equipment in order to be able to practice in some DevOps concepts.
      
      Some of the skills I gained through this process are:

      - <b>Kubernetes</b>,
      - <b>Ceph & GlusterFS</b> storage for Kubernetes,
      - <b>Custom CI/CD tools</b>,
      - <b>PiHole</b> network protection,
      - Basic <b>Network LAN</b> knowledge,

  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: Guardian Telematics
        caption: 2019 - Today
        description: | # this will include new lines to allow paragraphs
          <b>DevOps Engineer, System's Architect and Team leader:</b>

          My and my team are making sure that the companies products are highly available and can be scale up or down depending on the demand.
      - layout: left
        title: Guardian Telematics
        caption: 2018 - 2019
        description: | # this will include new lines to allow paragraphs
          <b>Backend Developer Team Leader:</b>

          I was spectating the software production process while being a part of it, as an active developer. My role was to design the software, to 
          code some programing features, to provide help to the other members of the team, to orchestrate the tasks and to make sure that we meet the 
          goals of the business.
      - layout: left
        title: Harokopeio University of Athens
        caption: 2016 - 2017
        description: | # this will include new lines to allow paragraphs
          <b>Linux Administrator / IT Technician</b>

          Every year Informatics and Telematics Department of Harokopeio University selects four students that are in the last year of  them education. 
          The  four  students  can  work  as  a “networks  and  technical  support  unit” for the  university  for  a  year  as  a  mean  for  them  to  gain  hands  on 
          experience.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harokopeio University of Athens
        caption: 2013 - 2017
        sub_title: Bachelor of Science on Computer Science and Telematics.
        description: | # this will include new lines to allow paragraphs
          Got my first degree from Harokopeio University in Computer Science and Telematics to the minimum of Education duration. I got the attention 
          of some of the university professors Due to my high performances on almost all university projects
      - layout: left
        title: Harokopeio University of Athens
        caption: 2017 - 2020
        sub_title: Master of Science on Computer Science and Telematics.
        description: | # this will include new lines to allow paragraphs
          I have won two scholarships due to my high grades during the semesters.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
